# Generated by Django 2.2.3 on 2019-11-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
