# Generated by Django 2.2.3 on 2019-11-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191123_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('-created_time',), 'verbose_name': '栏目', 'verbose_name_plural': '栏目'},
        ),
        migrations.AlterField(
            model_name='post',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Column', verbose_name='栏目'),
        ),
    ]
