# Generated by Django 2.2.3 on 2019-12-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20191207_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_time',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
